### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by ramsyiq** [polusgg/Town-Of-Us#102]
Can you update the source code? or is it no longer open source?

**Comment by cathalaherne2** [comment]
source code is right here https://github.com/slushiegoose/Town-Of-Us/tree/master/source/Patches

**Comment by VanillaChan6571** [comment]
> 
> 
> source code is right here https://github.com/slushiegoose/Town-Of-Us/tree/master/source/Patches

Correct but @slushiegoose has not updated the source for 2.0.1 so just gotta wait.

**Comment by ramsyiq** [comment]
> > source code is right here https://github.com/slushiegoose/Town-Of-Us/tree/master/source/Patches
> 
> Correct but @slushiegoose has not updated the source for 2.0.1 so just gotta wait.

i think @slushiegoose no longer share the source since they're merging with polus.gg

**Comment by MrFawkes1337** [comment]
> > > source code is right here https://github.com/slushiegoose/Town-Of-Us/tree/master/source/Patches
> > 
> > 
> > Correct but @slushiegoose has not updated the source for 2.0.1 so just gotta wait.
> 
> i think @slushiegoose no longer share the source since they're merging with polus.gg

That depends if he's still shipping with Essentials included with Town of Us, and if he changed code from other open source projects to his own implementation ofc. If not, he has to publish it under GPL iirc.

**Comment by amsyarasyiq** [comment]
> > > > source code is right here https://github.com/slushiegoose/Town-Of-Us/tree/master/source/Patches
> > > 
> > > 
> > > Correct but @slushiegoose has not updated the source for 2.0.1 so just gotta wait.
> > 
> > 
> > i think @slushiegoose no longer share the source since they're merging with polus.gg
> 
> That depends if he's still shipping with Essentials included with Town of Us, and if he changed code from other open source projects to his own implementation ofc. If not, he has to publish it under GPL iirc.

ight so we make a DMCA complaint?

**Comment by MrFawkes1337** [comment]
> > > > > source code is right here https://github.com/slushiegoose/Town-Of-Us/tree/master/source/Patches
> > > > 
> > > > 
> > > > Correct but @slushiegoose has not updated the source for 2.0.1 so just gotta wait.
> > > 
> > > 
> > > i think @slushiegoose no longer share the source since they're merging with polus.gg
> > 
> > 
> > That depends if he's still shipping with Essentials included with Town of Us, and if he changed code from other open source projects to his own implementation ofc. If not, he has to publish it under GPL iirc.
> 
> ight so we make a DMCA complaint?

I mean you could? But since you (probably) Didn't provide any of the code base, they would laugh at your DMCA request and refuse it. It would need to come from somebody like Commando (Essentials Lib) or Reactor Devs since the source is outdated.

**Comment by amsyarasyiq** [comment]
oh wait i cant close this
