### ISSUE TITLE
among us isnt recognizing me when mods are installed v2021.4.14s

### ISSUE THREAD

**Issue by Chaosphoenix931** [polusgg/Town-Of-Us#104]
when i have the mods installed the game doesnt recognize my account

**Comment by Chaosphoenix931** [comment]
i also have the correct version

**Comment by DZDiamondGaming** [comment]
I have installed the latest version of this mod however when I go to run the game it doesn't run the mods. I have tried many different methods and still no luck.

I also followed this guide and didn't work.

1. Download the latest TownOfUs Mod zip file from slushiegoose on GitHub.
2. Extract the contents of the zipped folder using a program like WinRar or 7Zip.
3. Locate the root folder for Among Us. The easiest way to find this file path is to open Steam, navigate to Library, right-click Among Us, navigate to Manage, and choose Browse Local Files.
4. Move the extracted mod files into the Among Us root folder. This is the folder containing the Among Us.exe file.
5. Launch Among Us.

If there is an alternate guide then please let me know so I can attempt. I have the latest version installed.
