### ISSUE TITLE
Among us server can't authentificate me using the mod even as guest account

### ISSUE THREAD

**Issue by Dorin120** [polusgg/Town-Of-Us#105]
Also btw yesterday it was working also i reinstalled and still not working

**Comment by Chaosphoenix931** [comment]
I have the smae issue dont know if the new update somehow messed with mods but i think we have to wait for a fix

**Comment by IngameMyst** [comment]
yea i have the same issue

**Comment by carbone15** [comment]
town of us is compatible with versin 2021.4.12s and there is a version 2021.4.14s in steam so it s not yet comaptible and I don't know if it will be

**Comment by Loremonn** [comment]
> town of us is compatible with versin 2021.4.12s and there is a version 2021.4.14s in steam so it s not yet comaptible and I don't know if it will be

That's what I thought might be the problem as well...

**Comment by CreeperDeathMatch67** [comment]
innersloth always wants the last laugh when it comes to mods

**Comment by Dorin120** [comment]
yeah well thank you very much yall :D

**Comment by Dorin120** [comment]
they updated it :D

**Comment by lasershow01** [comment]
hey townof us was working fine yesterday but when i loged in this morning it kept saying i needed an account even though i got one

**Comment by lasershow01** [comment]
SO I FOUND THIS OUT some of the lobbies dont authenticate u but some lobies do its strange and i hope among us and slushiegoose can update

**Comment by Pixelplayz2215YT** [comment]
Download the new update v2.0.2 it's fixed!
