### ISSUE TITLE
[BUG] Walking through walls

### ISSUE THREAD

**Issue by not-3than** [polusgg/Town-Of-Us#107]
You can walk through walls while holding the N key. Please fix as this can be heavily abused.

**Comment by ugackMiner53** [comment]
### Can confirm, this does actually happen

What I think happened is that slushiegoose accidently left a debug setting in the mod during the **2.0.1** update.

It is in the **"ResetAnim"** class, in the PostFix

```
		public static void Postfix(PlayerControl __instance)
		{
			bool flag = __instance != PlayerControl.LocalPlayer;
			if (!flag)
			{
				bool keyInt = Input.GetKeyInt(98);
				if (keyInt)
				{
					PlayerControl.LocalPlayer.MyPhysics.ResetMoveState(true);
					PlayerControl.LocalPlayer.Collider.enabled = true;
					PlayerControl.LocalPlayer.moveable = true;
					PlayerControl.LocalPlayer.NetTransform.enabled = true;
					MessageWriter messageWriter = AmongUsClient.Instance.StartRpcImmediately(PlayerControl.LocalPlayer.NetId, 111, 1, -1);
					messageWriter.Write(PlayerControl.LocalPlayer.PlayerId);
					AmongUsClient.Instance.FinishRpcImmediately(messageWriter);
				}
				bool flag2 = !ResetAnim.isHeldDown;
				if (flag2)
				{
					ResetAnim.resetAnim = PlayerControl.LocalPlayer.Collider.enabled;
				}
				bool keyInt2 = Input.GetKeyInt(110);
				if (keyInt2)
				{
					PlayerControl.LocalPlayer.Collider.enabled = false;
					ResetAnim.isHeldDown = true;
				}
				else
				{
					ResetAnim.isHeldDown = false;
					PlayerControl.LocalPlayer.Collider.enabled = ResetAnim.resetAnim;
				}
			}
		}
```

I have no clue which specific file has this in it, but I know what class it is in, and it can easily be fixed with an assembly patch using dnSpy

**Comment by not-3than** [comment]
> ### Can confirm, this does actually happen
> What I think happened is that slushiegoose accidently left a debug setting in the mod during the **2.0.1** update.
> 
> It is in the **"ResetAnim"** class, in the PostFix
> 
> ```
> 		public static void Postfix(PlayerControl __instance)
> 		{
> 			bool flag = __instance != PlayerControl.LocalPlayer;
> 			if (!flag)
> 			{
> 				bool keyInt = Input.GetKeyInt(98);
> 				if (keyInt)
> 				{
> 					PlayerControl.LocalPlayer.MyPhysics.ResetMoveState(true);
> 					PlayerControl.LocalPlayer.Collider.enabled = true;
> 					PlayerControl.LocalPlayer.moveable = true;
> 					PlayerControl.LocalPlayer.NetTransform.enabled = true;
> 					MessageWriter messageWriter = AmongUsClient.Instance.StartRpcImmediately(PlayerControl.LocalPlayer.NetId, 111, 1, -1);
> 					messageWriter.Write(PlayerControl.LocalPlayer.PlayerId);
> 					AmongUsClient.Instance.FinishRpcImmediately(messageWriter);
> 				}
> 				bool flag2 = !ResetAnim.isHeldDown;
> 				if (flag2)
> 				{
> 					ResetAnim.resetAnim = PlayerControl.LocalPlayer.Collider.enabled;
> 				}
> 				bool keyInt2 = Input.GetKeyInt(110);
> 				if (keyInt2)
> 				{
> 					PlayerControl.LocalPlayer.Collider.enabled = false;
> 					ResetAnim.isHeldDown = true;
> 				}
> 				else
> 				{
> 					ResetAnim.isHeldDown = false;
> 					PlayerControl.LocalPlayer.Collider.enabled = ResetAnim.resetAnim;
> 				}
> 			}
> 		}
> ```
> 
> I have no clue which specific file has this in it, but I know what class it is in, and it can easily be fixed with an assembly patch using dnSpy

That's what I was thinking was happening, some debug thing they forgot to remove.
