### ISSUE TITLE
Modifier text gets cut off

### ISSUE THREAD

**Issue by NoahsArkOfficial** [polusgg/Town-Of-Us#108]
So since this update, whenever I play a game with modifiers, its as if the text has been zoomed in and it gets cut off the screen. this wasnt an issue in the previous update and it fit perfectly but for some reason this update the text is larger. Im unsure how to fix it or whether its just the update.

**Comment by not-3than** [comment]
> So since this update, whenever I play a game with modifiers, its as if the text has been zoomed in and it gets cut off the screen. this wasnt an issue in the previous update and it fit perfectly but for some reason this update the text is larger. Im unsure how to fix it or whether its just the update.

Can confirm on v2.0.2

**Comment by MrFawkes1337** [comment]
can also confirm, was not having this issue with 2.0.1, im thinking its something with the new update however, as TextRenderer was removed. It'll be fixed in time now they know :)

**Comment by PassyFox** [comment]
Can confirm this with the latest builds for among us and the mod. Hopefully this gets fixed soon :)
