### ISSUE TITLE
Issue with Altruist and snitch interaction

### ISSUE THREAD

**Issue by uinan** [polusgg/Town-Of-Us#111]
Tested with the v2.0.2 mod version on Polus map.
There is an issue when the Snitch is killed while he have many tasks left and gets successfully revived by the Altruist. The imposter automatically gets an arrow pointing down to the Snitch, even though he still have some tasks to be done.

**Comment by Eddiemate** [comment]
I was testing Altruist on 2.0.4 earlier, and I got the same arrow pointing to the lover I revived. I think the impostors just now get a warning that a player has been revived by the Altruist.
