### ISSUE TITLE
Enhancement: Lover Role Suggestion

### ISSUE THREAD

**Issue by blitzboy01** [polusgg/Town-Of-Us#122]
Might I suggest that, when one of the lovers die the other lover is given the chance to kill their partner's killer but, the catch is that when they find and kill the killer, they also die. They could also give the partner the chance to kill the killer within a few seconds.

**Comment by francescobau** [comment]
That's a great idea!
A chance to have a revenge, and, when it's fulfilled, it can die in peace.
Also, there is another "catch": it can be considered as a misfired Sheriff kill xD
And, if the lover failes to fulfill its revenge, and there's a meeting, it will die.

**Comment by blitzboy01** [comment]
Yeah, it should be limited to when both lovers are crewmates. It would mess up the mechanics if one of them is an impostor.

**Comment by Larnest** [comment]
i saw a situation, where impostor killed lover-impostor instead of crewmate, while lover-impostor and crewmate were in one place
[video](https://youtu.be/9NnXs0PD3mY?t=20231)

**Comment by blitzboy01** [comment]
That looks like a bug that should not have happened, considering both are impostors
