### ISSUE TITLE
Some Ideas for new roles, modifiers, or game modes

### ISSUE THREAD

**Issue by jamesburrow23** [polusgg/Town-Of-Us#125]
First off @slushiegoose i've gotta say I'm so impressed with what you've built, I think you are single handedly keeping Among Us relevant and highly entertaining!

As I was watching Ze and Chilled last night I heard them mention so new roles that might be interesting and I took the liberty to expound on some of their ideas and also have some ideas of my own. 

If I knew this language I would do my best to contribute directly, but sadly I'm not nearly as skilled as you are.

### **Team: Crewmates**
The Medium is a Crewmate that has the ability to see ghosts (either on cooldown as an ability or all the time). 
They have an ability once per game to summon a "haunting" in a meeting to kill another player (you could even limit this to a minimum of number of dead players before they can summon them), if they pick a baddie then the Medium survives and the bad player dies, if they pick another crewmate role then they would die (very similar to the current assassin role)

### Game Options
| Name | Description | Type | Default |
|----------|:-------------:|:------:|:------:|
| Medium | The percentage probability of the Medium appearing | Percentage | 0% |
| Medium can see ghosts on cooldown | Whether the Medium's ability to see ghosts is on cooldown | Toggle | True |
| Medium can see ghosts at all times | Whether the Medium's ability to see ghosts is constant | Toggle | False |

### **Team: Imposters**
The Teleported is an Imposter that has the ability to teleport themself or choose to teleport a body to a random location on the map on cooldown.  It's useful if they kill and want to throw off the crewmates with where the kill happened, or if they need to make a quick getaway (but be careful since you could teleport into a spot where other people would see you appear)

### Game Options
| Name | Description | Type | Default |
|----------|:-------------:|:------:|:------:|
| Teleporter | The percentage probability of the Teleporter appearing | Percentage | 0% |

# Modifier/Game Modes

### **Applied to: Crewmates** (This could also be an interesting game mode where every crewmate is terminal and is rushing to do tasks to survive)
At the start of each round the Terminal would see their internal body temperature next to their name, as the round progresses this temperature will continue to slowly rise.  If their temperature gets above a certain number they die, the only way to lower their temperature is to complete tasks (shorter tasks would lower it a little bit while longer tasks would decrease their temperature more).   After they complete all of their tasks they stabilize at a healthy temperature. 

### Game Options
| Name | Description | Type | Default |
|----------|:-------------:|:------:|:------:|
| Terminal | The percentage probability of the Terminal appearing | Percentage | 0% |
| Terminal starting temperature | The starting body temperature of  | Number | 98.6 |
| Terminal lethal temperature | The body temperature when death occurs | Number | 107.5 |

### ** New Game Mode **
At the start of the round players are divided into 2 teams, everyone has a kill button on a 3 second cool down.  Every 60 seconds a "hill" is moved around the map (this would be a room on the map with a visual outline indicating it's the active hill).  Players would battle back and forth to seize the hill, if a player dies they respawn 3 seconds later and try again to take the hill.  Victory is decided after one team has enough time in the hill.

Basically think of King of The Hill mode from the days of Halo

### ** New Game Mode/End Game Finale **
Either as a separate game mode or at the end of a round the players would enter an infection survival mode.  If added to the end of the game then the first two players who died in the last round start as infected crewmates who are trying to spread their disease to the rest of the ship.

Infected players spawn in a separate part of the ship. Every player gets a kill button but Healthy crewmates are slightly faster than infected crew mates but infected people have a shorter kill cooldown.  If you get "infected" (i,e someone who is infected kills you) then you respawn as an infected crewmate.

The game ends when either all of the crewmates are sick or the timer runs out (in that case the healthy crewmates would all win).  Infected crewmates would have a visual indicator (something like a green overlay their character)

Basically think of the infection mode from the days of Halo

**Comment by MandyMeindersma** [comment]
I think they want suggestions for new roles in their discord, there is a special channel and bot for it but I am not sure.
