### ISSUE TITLE
Proximity Voice Chat Not Compatible

### ISSUE THREAD

**Issue by datonenikki** [polusgg/Town-Of-Us#126]
My friends and I have tried using Crewlink with this mod, but it doesn't work- we tried running the vc mod by itself and it worked just fine, but the problems came when Town of Us was added. We don't know what to do, and we really wanna play with proximity voice chat.

**Comment by PassyFox** [comment]
can you check if you have the correct version of the mod with the correct version of among us? we have installed a clean install from steam and everything works fine for us

**Comment by TwilightZebby** [comment]
@datonenikki If all else fails, you can try using [BetterCrewLink](https://github.com/OhMyGuus/BetterCrewLink)? It's a fork of the original.
