### ISSUE TITLE
Medic's shield is not effective (impostors can kill anyways) + Child glitches at the ladders in the Airship. Suggestions for the Child

### ISSUE THREAD

**Issue by francescobau** [polusgg/Town-Of-Us#128]
The title says it all...

- When a Medic shields any kind of Crewmate, any Impostor is still able to kill the shielded player.

- A Child can't use the ladders properly, and, when it can, it gets stuck at the ladders.

Also, I have some suggestions for the Child... Feel free to choose at least one of them! And other ideas would be really great!
1. The Child should be able to HIDE in the vents, since everyone already knows who the Child is, and it is tiny enough to fit in xD
2. If the Child finishes the tasks, everyone wins!
2.1. (alternative) A Child does not have any task to do
3. PIGGYBACK ABILITY. The Child can "piggyback" at the top of another Crewmate, so, if an Impostor tries to kill the Child, the Crewmate will "tank it". The piggyback is possible for a limited time (Piggyback cooldown and Piggyback time). If the Child piggybacks at the top of an Impostor, that Impostor can... eat the Child xD
4. The Child can not talk in the Chat, and it can not vote. But it knows who the Impostors are.
5. [other ideas?]

**Comment by Sinus32** [comment]
Impostor is still able to kill the shielded player by using 'Q' key on keyboard.

**Comment by francescobau** [comment]
Yes! Exactly!
And, well... That shouldn't happen, right?

**Comment by Maryjane007** [comment]
@francescobau That is right and also if you have ideas go to slushiegoose's discord server and you will know what to do!
