### ISSUE TITLE
Aspect Ratio

### ISSUE THREAD

**Issue by Will1022** [polusgg/Town-Of-Us#129]
The texts on the left only work at 16: 9, everything else does not work.

**Comment by LorDawid** [comment]
same issue

**Comment by ubiquish** [comment]
Curious why this issue was closed.  (Confirmed to still exist as of TOU_214.)

Apologies if this is a duplicate -- I don't see any other open issues that seem to match, and the original issue was simply marked "closed" with no further explanation.
