### ISSUE TITLE
Arsonist Can't Win If There is a Child

### ISSUE THREAD

**Issue by BadScientist** [polusgg/Town-Of-Us#131]
The arsonist gets a "Defeat: Child Killed" screen if they succeed in dousing and igniting all players when one player is a child. This makes the arsonist role unwinnable if there is a child in the game.

Mod Version: 2.0.2
Game Version: 2021.4.14s

**Comment by Sinus32** [comment]
+1
I also experienced this issue.

**Comment by KyaniteKirin** [comment]
+1

**Comment by slimsy135** [comment]
+1
