### ISSUE TITLE
Investigator Lag (FPS drops)

### ISSUE THREAD

**Issue by KyaniteKirin** [polusgg/Town-Of-Us#133]
This has happened not just to me, but everyone who has had investigator in my group. We have changed the settings so that footsteps appear less frequently or appear at different sizes but nothing seems to fix the sudden fps drops.
I have a Ryzen 5, 16 gb of ram and an RTX 2080 so it's definitely not hardware.
I've seen some people stream and play investigator without the fps drops but not sure how they manage to do that.

FPS drops happen every 1-2 seconds. The game runs smoothly for everyone else in the lobby, only the investigator lags. No other roles have this issue. 

Among Us version _2021.4.12s & 2021.4.14s_ **|** Mod version _2.0.2_

**Comment by KH0DIIN** [comment]
taut does happen Investigator is so bad and the Mod game stutters a lot anyways with the Mod

**Comment by KyaniteKirin** [comment]
I have no problem with the game itself. I'd say if the game itself is lagging that may be because your hardware is struggling a bit to run the game plus the mod. I only have a problem with the investigator role, so not sure if it's not optimized in the latest version or if it's a problem on my end. I'm just skeptical about it being on my end because my hardware is quite good and I'm not the only person having issues with investigator lag.

If I play again anytime soon, I may look into recording my gameplay to show the difference between frames when playing any other role compared to playing investigator but hoping the problem may be fixed before I play again or someone has some insight that may help stop the spikes. My personal guess may be optimization is needed within the mod itself?

**Comment by MrFawkes1337** [comment]
Its not just you. Its down to Slushie to fix, and he will, just give him time.

**Comment by KyaniteKirin** [comment]
> Its not just you. Its down to Slushie to fix, and he will, just give him time.

Ah awesome then :) Was wondering if maybe my settings may have been wrong. My friends and I are patient, looking forward to future updates 😀

**Comment by ryancwilliams** [comment]
I am also experiencing this issue. I am running a RTX 2080. My FPS goes from 60 normally to less than 20 when I am the investigator. It interferes with my ability to do some tasks. 

Is there any information I can contribute to help solve this issue?

**Comment by KyaniteKirin** [comment]
> I am also experiencing this issue. I am running a RTX 2080. My FPS goes from 60 normally to less than 20 when I am the investigator. It interferes with my ability to do some tasks.
> 
> Is there any information I can contribute to help solve this issue?

I have noticed that the lag spikes get a bit better if you increase the interval of the footprints and decrease how long they last. I'm almost certain now its just poor optimization or there's a light problem with the code that makes it lag, but if not everyone is experiencing this, it makes me wonder what's different about our installation compared to theirs

**Comment by MrFawkes1337** [comment]
The issue is in how the updates are called, which is why you lag. I’m pretty sure it’s called every frame through HudManager.Update, which is where the issue lies.

**Comment by vperpl** [comment]
0 issues with investigator here. on 2 pcs one low end 2nd highend. so it must be something in system related

**Comment by MrFawkes1337** [comment]
> 0 issues with investigator here. on 2 pcs one low end 2nd highend. so it must be something in system related

impossible; I run a Ryzen 9 3900X paired with 32GB DDR4 3600MHz Ram, and an RTX 2070 Super. I don’t even get bottlenecks on my VR content when I stream, but just play a bit of modded Among Us and get 1 FPS? Uh, what?

**Comment by ryancwilliams** [comment]
> 0 issues with investigator here. on 2 pcs one low end 2nd highend. so it must be something in system related

For me it does not happen with 4 people but it does happen with more players. At 8 players it is almost unplayable. At 10 it is unplayable.  The more players their are the worse it is.

Given that I am not the only person with this issue I would assume that the code has some indeterminant behavior that is only running on the client that is unique to the Investigator.

Indeterminant behavior means that the code is running differently on some systems. It could be my hardware causes this issue but the code being indeterminant makes this issue possible.

On the system that I am experiencing this issue on my CPU is Intel Haswell E (5th gen intel) and my GPU is a 2080.

**Comment by ryancwilliams** [comment]
Polus Support on the Discord just replied to me with this.
