### ISSUE TITLE
The Snitch Warning

### ISSUE THREAD

**Issue by viper2kx** [polusgg/Town-Of-Us#134]
I am relatively new to Among Us in general (Vanilla & modded).
I was an Imposter on Polus, and the Snitch was also in the match. The game flashed what appeared to be Olive Green (more green, a little yellow), and I thought the Medic shielded me and an attempt on my life happened (which was weird, because I was alone)... or the medic died. I run to the button and outed myself as an imposter.

Suggestion: The warning that the Snitch is close to finishing their tasks should be a brighter yellow.

**Comment by blitzboy01** [comment]
I would suggest the colours, either blinking or color blind friendly.

**Comment by viper2kx** [comment]
> I would suggest the colours, either blinking or color blind friendly.

Blinking could cause seizures, color-blind friendly would be better.

Or just plain messages like "Beware: The Snitch is almost done with their tasks" or when someone is the Medic display a message similar to "An attempt was made on the shielded person's life"
