### ISSUE TITLE
Question/Altruist + Lover

### ISSUE THREAD

**Issue by kotkowski** [polusgg/Town-Of-Us#136]
What happens when altruist revives one of the lovers?...

If nothing like that was implemented, I have 2 suggestions that could be alternated in settings -

1) Revived Lover revives as Crewmate
2) Revived Lover instantly commits suicide (aka. Romeo and Juliette story)

**Comment by Eddiemate** [comment]
A late response, but I just tested this since the question really interested me. Currently on 2.0.4, regardless of the circumstances if both lovers are dead then they get revived together. Even if both lovers die together is disabled, and if one of the lovers died in an earlier round.

**Comment by MatesV13** [comment]
Yes, i think it makes sence for them to be revived together if they die together. However, if "both lovers die together" is disabled, i think it would make more sence not to revive both, since both didn't die together. Maybe a bug?
