### ISSUE TITLE
Enhancement: Announce Arsonist

### ISSUE THREAD

**Issue by joelaw9** [polusgg/Town-Of-Us#139]
I'd like to propose a new rule that announces that there's an arsonist at the beginning of the round.

With all the extra roles and rules imposters almost never have much of a time crunch in Town of Us games. If arsonists could be announced at the beginning of the round that creates a strong incentive for imposters to speed run/vent play more/etc. Alternate play.

**Comment by not-3than** [comment]
Would be much better if there was just an announcement that there was an arsonist instead of announcing who it was.

**Comment by joelaw9** [comment]
Of course, I didn't mean that it'd announce who it was. Then they'd just kill them.
