### ISSUE TITLE
When Miner jumps in their vent they get DC'd

### ISSUE THREAD

**Issue by Maygus** [polusgg/Town-Of-Us#144]
When Miner jumps in their vent they get DC'd

Running on Impostor 188

**Comment by kotkowski** [comment]
didn't happen to me

**Comment by Hardel-DW** [comment]
I tried to add a role that place Vent, when entering it there is indeed a forced disconnection.
A securtiy as been added in Among Us.

This bug don't appear on Freeplay, Local Game.
On Public Server is normal the AntiCheat block Custom Vent.
But on Custom Server on new Security is to remove.

Town Of Us need to update

**Comment by Maygus** [comment]
We have not used the role since 3 players in 3 seperate games experienced it.

It was the 3rd one doing it that made us realise it.
We only play on custom server, not public

**Comment by Lorn-Hukka** [comment]
I can confirm there is something wrong. Anybody who tries to enter into vent placed by miner is disconnected.

_Played on custom (latest) Impostor Server._
