### ISSUE TITLE
Connecting only to vanilla lobbys

### ISSUE THREAD

**Issue by Wojciechgc** [polusgg/Town-Of-Us#147]
When i installed the mod everything was working, when i go to Public it listed Town of Us lobbys but when i changed the language it's listing only vanilla lobbys now and i can't play because all lobbys are vanilla. I tried reinstalling Among Us and installing the mod again, clearing AppData but it still gives me only vanilla lobbys.

**Comment by MatesV13** [comment]
Usually there is no public ToU games. If you want to play with others, you can always join ToU discord.
Also, there should not be problems with playing in vanilla lobby. As long as you are not the host, then host will always have 0% on all roles, and game will play like vanilla normally.
