### ISSUE TITLE
Altruist + Jester

### ISSUE THREAD

**Issue by hawkerm** [polusgg/Town-Of-Us#149]
What should happen if the Altruist tries to revive the Jester? Should they be able to? We saw our Altruist just die which seemed wrong... (and the Jester was NOT revived)

v2.0.4

**Comment by MatesV13** [comment]
That is the point. Altruist can revive anyone - after some time playing we saw Jester revived, we saw Glitch revived, and we saw Imposter revived after killing by Sheriff, and then killing the Sheriff. This is somewhat of counter to Altruist: not every revived will be helpful for crew.

**Comment by hawkerm** [comment]
@MatesV13 maybe I should have been clearer. Our Altruist died, but the Jester was not revived. It sounds like reviving anyone should be possible, so this sounds like a bug?

**Comment by MatesV13** [comment]
Yes, he should be able to revive anyone. Are you sure cooldown (usually 10s) has passed already? If not, then target will not be revived, if something interups it (e.g. meeting or report body). If cooldown has passed, then i guess it it a bug.
