### ISSUE TITLE
Normal Among Us doesn't work anymore

### ISSUE THREAD

**Issue by itsFlippo** [polusgg/Town-Of-Us#15]
Since I installed this mod, I cant play the original or other mods.

I'll always start in the bottom of the start room in the color "bug-green" and with three "???".

What we done already:
- deinstalled all mods and the game from steam + folders
- restarted the computer
- installed everything new
- folders via steam examine for bugs

can anyone help us here?
(this problem happend to 3 of all 10 members in our lobby)

**Comment by zukulent0** [comment]
Ive also faced this problem before, this is because you used a color from the mod and when you switch back to normal among us, the game doesnt know what color are you and it gives you the green with the ???.

In order to fix it you need to install back the mod, change your color to one of the vanilla ones and remove the mod.

**Comment by nathanctech** [comment]
Head's up, I found another solution. In Windows, browse to `%USERPROFILE%\AppData\LocalLow\Innersloth\Among Us\` and delete the "userPrefs" file. This will "reset" your game and will allow it to work again.

**Comment by TomKyrre** [comment]
> Ive also faced this problem before, this is because you used a color from the mod and when you switch back to normal among us, the game doesnt know what color are you and it gives you the green with the ???.
> 
> In order to fix it you need to install back the mod, change your color to one of the vanilla ones and remove the mod.

zukulent0 is corrent. Play the Among Us with Town of Us mod, pick a color that is NORMAL color that only exists in the original. Then exit and you should be able to run normal among us. 

You can also do the nathantechs solution by deleting the file (file is called userPrefs or playerPref depending on type of installation source Steam/Direct Download/Microsoft Store)
