### ISSUE TITLE
[Role ideas] Neutral Assassin and Crew Assassin

### ISSUE THREAD

**Issue by Pimak** [polusgg/Town-Of-Us#151]
Sniper
==== 

Team
------
Crew

Name substitutes 
-----

- Crew assassin
- Judge
- Cap
- Captain

Description
------

The sniper can kill any neutral or any imposter role during a meeting by guessing the exact role.
If the sniper guesses wrong, he dies also. 

The killing animation should look exactly like an assassin so that player wouldn't know if it's a assassin kill or a snipe.

Settings
-------
The settings should be the same as the assassin.

Wisenheimer
====
Team
--------
Neutral

Name substitutions 
-------------
- Know-it-all
- Smarty
- Smarty-pants
- Concierge

Description
--------
The Wisenheimer needs to know every single role alive to win.
The default settings would be as follow : 
Each meeting, the Wisenheimer can guess for each player a role.
If it's the right role, the role stays under the name (only seen by the Wisenheimer).
If it's the wrong role, it just misses and nothing happens and the Wisenheimer can't guess that player this meeting.
Once he finds every role, he wins.

Settings
------ 
Name | Description | Type | Default
--- | --- | --- | ---
Wisenheimer | The percentage probability of the Wisenheimer appearing | Percentage | 0%
Wisenheimer needs to guess right to continue | The Wisenheimer can't keep guessing if the last guess was wrong | Toggle | False
Wisenheimer guesses per player per meeting | The Wisenheimer can only guess this number of time per player per meeting | Number | 1

**Comment by Maryjane007** [comment]
If you have any role ideas, then visit slushiegoose's discord server and I think you will know what to do after it!
