### ISSUE TITLE
[Random idea] Child is smoll

### ISSUE THREAD

**Issue by kotkowski** [polusgg/Town-Of-Us#152]
It should be able to fit in the vents - would be more interesting than just being a walking CCTV

**Comment by Maryjane007** [comment]
Good idea, but the child can only be a crewmate!

**Comment by Eddiemate** [comment]
That would mean there's two potentially venting Crewmates, one of which is a confirmed Crewmate. Considering impostors also usually kill someone who's hiding in a vent, it just makes Child insanely overpowered for Crew.
