### ISSUE TITLE
Black box with red code

### ISSUE THREAD

**Issue by pru12334** [polusgg/Town-Of-Us#157]
Hi whenever my friend tries to open the mod he gets a black box with red code on it followed by the normal game. The red code says something about preloader error. When i look at his normal game files he is missing one of the preloaders that i have so im assuming thats the issue but his game is fully updated and hes uninstalled and reinstalled. Not sure whats going on any help would be awesome!

**Comment by viper2kx** [comment]
Could be one of the following -
1. Among Us may not be up to date to work with the version mod.
2. Is your friend downloading the zipped folder from [here](https://github.com/slushiegoose/Town-Of-Us/releases/tag/v2.0.4)?
3. If your friend is using an Antivirus program (Norton, McAfee, Avast, etc...), add the modded game folder to the exclusion list helps.
