### ISSUE TITLE
Role Idea: Glass Cannon (Impostor)

### ISSUE THREAD

**Issue by N0rbi** [polusgg/Town-Of-Us#158]
Low cooldown impostor, that can not:

- report bodies
- use sabotages
- open doors (optional)
- open vitals (optional)
- open comms (optional)

_Note:_ maybe instead of low cooldown it could have 2 charges of kills, but needs to wait 2 times the kill cd to double kill.

**Comment by balloplayz** [comment]
great idea nobri want this role added two great idea
