### ISSUE TITLE
When i start the game its automaticly runs in the background and i can't do anything PS. im using epic games version

### ISSUE THREAD

**Issue by Tofix26** [polusgg/Town-Of-Us#163]

**Comment by NuclearThief** [comment]
the epic games version of the mod is not out yet,

**Comment by noemsus** [comment]
So they're is not gonna be a Epic Games version of Town of Us, but in the future, when the Owners of Town of Us finish the Polus.gg server, that's gonna Town of Us be in it, they said that there gonna try to make the Among Us Epic Games Version to work on Polus.gg, so wait.

**Comment by NuclearThief** [comment]
The EGS ver is now supported but the way how you do it is different
