### ISSUE TITLE
When we the new version be available to the public?

### ISSUE THREAD

**Issue by Greenmangamer** [polusgg/Town-Of-Us#166]
I've seen streamers play the newest version for weeks (maybe a month) when will it be released for the rest of us?

**Comment by Eddiemate** [comment]
Probably never. Slushie has recently left Among Us modding, and 2.1.0 in its current state is still rather buggy.

**Comment by Ben-Alford** [comment]
I don't know about that... I've been seeing streamers post videos and streaming the 2.1.0 version for weeks now... it'd be nice if that could be made available in its current form, even with the promise of "no future updates/bugfixes will be coming".

**Comment by jcoffm** [comment]
Even if it won't be released as a stable release, its already being distributed. The 2.1 code must be made available in order for the project to comply with the terms of the GPL.
