### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by mehran5801** [polusgg/Town-Of-Us#170]
it is an idea only
is there anyway to make an android version of this mod??
maybe apk modification or any other method to make an android version?
there are too many users that can only play on android OS...

**Comment by amsyarasyiq** [comment]
yes, but it is not that easy and not worth it

**Comment by SnowTheSnow** [comment]
I know you already responded, and me asking probably won't make much difference- but please consider making a mobile version of the mod. There's a lot of people want to play the game with the mod but can't.
