### ISSUE TITLE
Feature: Fake Role

### ISSUE THREAD

**Issue by ApostropheM** [polusgg/Town-Of-Us#172]
Since streamers always make a rule against role calls, I thought it might be a good idea to add a Fake Role option. Imposters (and maybe Neutral roles) would get fake roles alongside their lists of fake tasks. These roles would be possible to get, so that the imposters don't need to worry about whether or not someone already has that role. For a number of roles, they wouldn't be able to prove it, but having something to claim would still help.

**Comment by N0rbi** [comment]
Nice idea. There could be a twist in it: the impostor can use the skill available for the role, but gets a **huge** debuff on the kill cooldown.

**Comment by Eddiemate** [comment]
I like the idea, but since most role claims can be easily disproven it's just easier for a knowledgeable impostor to claim a role that people can't just go "Except you haven't done this thing, so you're just lying"

**Comment by ApostropheM** [comment]
Time Lord, Swapper, Mayor, and sometimes Guardian can't really be faked, but roles like Engineer and Sheriff or Snitch and Spy are really just held back by not knowing whether or not someone else will contest you.
A way to use the role sounds difficult to balance but possibly interesting. A bunch of roles break. Imposters controlling meetings removes the main aspect of crew, and roles like Altruist kind of don't make any sense.
