### ISSUE TITLE
New Version of among us

### ISSUE THREAD

**Issue by MattyMan21** [polusgg/Town-Of-Us#173]
A new version of among us has been released and the mod is not working for me. I was told to go on the discord server but there is no link.

**Comment by Alfredo1802** [comment]
yes i agree, my version is v2021.5.25.2s

**Comment by H3llzscout** [comment]
If you follow the directions posted in the polus.gg discord you will be able to play the Town of Us mod.

**Comment by H3llzscout** [comment]
For peeps who don't have access to the Polus.gg discord Server here are the instructions:

Steam installation:
1: Go to your Steam library
2: Right-click Among Us > click Manage > click Browse local files
3: In the File Explorer, delete the entire Among Us folder
4: Go back to your Steam library
5: Right-Click Among Us > click Properties... > click LOCAL FILES
6: Click on VERIFY INTEGRITY OF GAME FILES...
7: Wait for Steam to download a clean version of Among Us
8: Duplicate the new Among Us Folder
9: Rename it to something like Among Us - ToU 2.0.4
10: Copy or move the contents of the Town Of Us zip file into that new folder
11: Finally, launch Among Us.exe from that folder

**Comment by Savqu** [comment]
@H3llzscout 
He knows how to install. It's just a mod. TOU 2.0.4 is for an Among Us version 2021.5.10s. The newest version of Among Us is 2021.25.2s

**Comment by H3llzscout** [comment]
I have the newest version and followed the posted instructions exactly as they were handed typed out and was able to play town of us.

**Comment by H3llzscout** [comment]
@Savqu I have the updated version as well.  I followed those instructions I posted exactly as they are written out and was able to utilize the mod
