### ISSUE TITLE
Bug Report: Role Names are Doubled on Match Start Screen

### ISSUE THREAD

**Issue by BadScientist** [polusgg/Town-Of-Us#175]
**Environment:**
Among Us Version: 2021.5.10s (Steam)
Town of Us Version: 2.0.4
OS: Windows 10 Home, 64-bit
CPU: AMD Ryzen 9 3950X
GPU: NVIDIA GeForce RTX 2080Ti
Network: Ethernet (300 Mbps down, 25 Mbps up)

**Steps to Reproduce:**
1. Start a match.
I was unable to determine more specific steps to reproduce this bug. It occurs about 50% of the time, regardless of the role received by the player. If anyone has more detailed steps, please add them to this report.

**Expected Result:**
One copy of role name should be displayed on the match start screen above the player portrait.

**Actual Result:**
The animated role name drops down as usual, but a second static copy of the name is also displayed, overlapping the animated one.

![image](https://user-images.githubusercontent.com/29133943/120940122-3e4b5e00-c6e1-11eb-9b51-c9c02b254bdf.png)
![image](https://user-images.githubusercontent.com/29133943/120940126-43101200-c6e1-11eb-86fb-0538bd460b42.png)
![image](https://user-images.githubusercontent.com/29133943/120940129-46a39900-c6e1-11eb-9d2e-9d86e6c33800.png)

**Severity (0 - 4):**
1 - This issue is mostly cosmetic, but it may make the text harder to read for some users.

**Comment by NotSugden** [comment]
for reference this issue occours whenever you have a modifier, the modifier text isn't generated properly and does this
