### ISSUE TITLE
Morphling killed Janitor

### ISSUE THREAD

**Issue by nylonW** [polusgg/Town-Of-Us#179]
I don't know why and how but morphling killed Janitor instead of Snitch scanning in medbay. Snitch also had medic's shield

**Comment by Scamper10** [comment]
If there was a spy in the game and the settings were a certain way, that is possible

**Comment by robertpbaxter** [comment]
My friends and I don't play with the Spy in our settings. A morphing teammate killed me as the camouflager two rounds in a row.

**Comment by ProteinGolem** [comment]
I've seen another player experience this as well. It's not a bug, it's an unintended feature 🤣
