### ISSUE TITLE
czapka ognista

### ISSUE THREAD

**Issue by Ognisty17** [polusgg/Town-Of-Us#196]
te ogniste rogi są one są zbyt małe i nie wiem czemu tak jest więc proszę o je powiększenie i wycelowanie ich na głowie w among us , pozdrawiam Streamer Ognisty17 :D

**Comment by przebor** [comment]
Just informing you that no one from the devs speak Polish so no one understands what you mean :)

**Comment by Ognisty17** [comment]
to weź im przetłumacz proszę bo mi bardzo na tym zależy ;(

**Comment by przebor** [comment]
te ogniste rogi są one są zbyt małe i nie wiem czemu tak jest więc proszę o je powiększenie i wycelowanie ich na głowie w among us , pozdrawiam Streamer Ognisty17 :D

These fire horns are too small and I don't know why. Please make them bigger and point them up.
Greetings, Ognisty17
