### ISSUE TITLE
New Critical Issues presented in 2.1.3

### ISSUE THREAD

**Issue by ProteinGolem** [polusgg/Town-Of-Us#200]
√ Fixed

√ Votes towards assassinated individuals do not get refunded
√ Colors of the spy don't show up on admin table
√ Hats don't appear anymore
√ When one person doesn't vote, the vote won't pass and the vote registers as a tie 
>> (I believe this is now fixed, with the caveat that when someone doesn't vote, if the vote doesn't pass as a crew eject, then the vote registers as a tie rather than between a skip and tie)

√ When someone leaves, the assassin sometimes no longer can assassinate
√ The giant's sprite is no longer giant

() Fix in progress

(Fixed?) When someone leaves, the arsonist has no douse button
(Fixed?) Cannot vote after someone leaves
(Fixed?) Phantom gets stuck when spawning in the admin room vent
(Fixed?) Altruist arrow continues to point to a revived individual's last location after a meeting is called if an altruist revive happens during a meeting
(Fixed?) Altruist after using their ability doesn't revive upon time rewind

(Fix being looked at) Snitch cannot see red names in meetings
(Fix in progress) Undertaker can drag and drop bodies into walls, making bodies unreportable
(Possibly Fixed?) Some crew roles, upon the disconnect don't have a "button disappearing problem", but rather a "button not working anymore" problem. Seems to be a rare but existent bug.
(Possibly Fixed?) Every single role has a "player disconnect" problem, making the role's buttons disappear in certain circumstances, except impostors.

- Needs attention

- Setting which allows the game to not end when there's a sheriff-impostor still alive (logic: both of them have kill buttons)
- Timelord induced revive during a body report can result in the revived player seeing the role colors of all people if the setting for "dead crew can see roles" is on
- Timelord is generally bugged on airship. Players may get rewinded into locations outside the map or near a wall.
- Reporting one's own dead body as a living player is possible with timelord
- Some tasks may become glitched when the timelord rewind occurs during the start or end of a task
- Shielding a player in a vent results the vented player able to move around the map invisible without ever venting out
- Executioner wins can result in impostor win screen
- Executioner sometimes spawns on the impostor's team
- Mayor doesn't get their votes refunded upon an assassination
- No option for self+medic flash indicator
- Phantom can sometimes move through walls, sometimes spawns in a vent and can't move, and sometimes can't complete tasks after finishing all the tasks if a player disconnects

**Comment by balloplayz** [comment]
yeah fix bugs creators

**Comment by NotSugden** [comment]
#202 fixes the assassin and arsonist bugs mentioned
#193 fixes the voting issues

**Comment by ProteinGolem** [comment]
TOU v2.1.4
Note: The arsonist still loses their douse button after an alive player leaves.

**Comment by ProteinGolem** [comment]
Jester/Executioner sometimes has a kill button... made for a funny game

**Comment by NotSugden** [comment]
😅 assassin and arso bugs definetly fixed in #233

**Comment by ProteinGolem** [comment]
- Every single role has a "player disconnect" problem, making the role's buttons disappear in certain circumstances, except impostors.

**Comment by NotSugden** [comment]
@ProteinGolem i just tested seer & medic and had no issues with a player DC, arsonist and assassin are fixed in #233, can you give me the log files from when this happened and or give specific reproduction steps

**Comment by ProteinGolem** [comment]
@NotSugden I've personally seen it twice with sheriff, once with medic, and twice with engineer. I'd have to play the game more to figure out how to reproduce the exact problem. I think it has something to do with a player disconnecting during an event, either a meeting or a time rewind, or possibly before/during game starts.

**Comment by NotSugden** [comment]
#248 will aim to fix most issues
