### ISSUE TITLE
[Suggestion] new Crewmate Role : Judge

### ISSUE THREAD

**Issue by GaranceF** [polusgg/Town-Of-Us#211]
**The role :**
Just like the assassin : the ability to kill during meetings if he can guess the role of an Impostor or of a Neutral role(if he misses ,he kills himself) 

**Why this role :**
This role isn't really necessary in 10 players or less games, but with more than 10 players games this role become really important , he is a good way to get rid of the Jester , Glitch... when the Sheriff is dead or not doing his job.

**The role's name :**
Judge name is just the one I come up with, but feel free to call it as u want.

**Comment by MrFawkes1337** [comment]
Basically just a good Assassin. It would be possible, and wouldn't require a massive role rewrite to do.
