### ISSUE TITLE
[Suggestion] update Assassin role

### ISSUE THREAD

**Issue by GaranceF** [polusgg/Town-Of-Us#212]
**Current problem**
The Assassin role (beside the bugs he has right now) has a flaw : during meetings he kills himself more than he kills Crewmates.

The thing is this role is really hard to play and you have 2 choices : take the risk to die and guess someone or just don't use your power unless you are very confident to not miss , aka almost never.

**Solution and update idea**
Give him a life counter : the number of time he can fail to guess without dying 
This way if this is a setting , he might not die right away and take more risks without being op 

Other update idea : 
Increase the maximum guess number setting

**Comment by CrispyBacon1999** [comment]
That's the entire point of the role. You aren't supposed to just guess, willy nilly, you should be confident in what role you're guessing on someone.
