### ISSUE TITLE
Meeting Issues

### ISSUE THREAD

**Issue by Tholmne** [polusgg/Town-Of-Us#213]
Playing tonight with people we had issues when the Glitch was added that people voted off were not dying if they were the glitch or an imposter. This problem only happened after we had the glitch as an option.

A few times it counted a majority vote ( 3 vs 1) as a tie vote. Most of the time it took two meetings to vote off a Glitch.

Maps used: The Skeld, Airship, Polus.

This was from the latest version of Among Us and Town of Us (Version 2.1.3)

**Comment by cybershard** [comment]
Please try with version 2.1.4

**Comment by Tholmne** [comment]
Will do next time we play and get back to you.

**Comment by Tholmne** [comment]
From our last games this issue seems to be fixed now
