### ISSUE TITLE
the mod will not run correctly

### ISSUE THREAD

**Issue by CharlieYT567** [polusgg/Town-Of-Us#219]
what i mean is instead of Town Of Us 2.1.4 running the vanilla version of Among Us is running instead if you could tell me how to fix that that would be great!

**Comment by CharlieYT567** [comment]
lol nvm

**Comment by dumbplayer2** [comment]
We provide support on Discord

https://discord.gg/Polus

**Comment by CharlieYT567** [comment]
if you have the same problem it could be bc you're stupid like me and downloaded the source code instead of the actual mod
