### ISSUE TITLE
[Bug] arrows pointing on snitch have disappeared when he is revived by time lord

### ISSUE THREAD

**Issue by ImSernik** [polusgg/Town-Of-Us#220]
Hello,
today i was playing some public and i found this bug
if the snitch is killed when he has finished his tasks, and time lord revived him, the impostors and the glitch lose the arrows pointing to him. However I don't know if it's always like that, but i think it is.

**Comment by MrFawkes1337** [comment]
Uhm, i'd have a guess that it's to do with the logic for Impostors recognising he's dead, but not revived from the Time Lord. Just going off the snitch code, they destroy all Impostor arrow instances when the Snitch dies, which is probably where the issue lies.

**Comment by ImSernik** [comment]
I think that is the case. Also, according to what you said, I'm pretty sure that if the altruist revived snitch there will be the same issue.
