### ISSUE TITLE
Error Loading TOU v2.1.4 -> Reactor 0.3.0-ci.38

### ISSUE THREAD

**Issue by Quicky107** [polusgg/Town-Of-Us#224]
Hi all,

As i said in the title, i have an error with the loading. What can i do for ? Thx

Here my cmd screen :

`[Message: Preloader] BepInEx 6.0.0-reactor.23 - Among Us

[Message: Preloader] BLEEDING EDGE Build #23 from dd899535f444a17128061a9ff96c17b85b9e6967 at reactor
[Info   :   BepInEx] System platform: Bits64, Windows
[Info   : Preloader] Running under Unity v2020.3.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:   BepInEx] Chainloader initialized
[Info   :Unhollower] Registered mono type UnhollowerRuntimeLib.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 4 plugins to load
[Info   :   BepInEx] Loading [Reactor 0.3.0-ci.38]
[Error  :   BepInEx] Error loading [Reactor 0.3.0-ci.38] : Exception has been thrown by the target of an invocation.
[Warning:   BepInEx] Skipping [Essentials 0.1.0] because it has a dependency that was not loaded. See previous errors for details.
[Info   :   BepInEx] Loading [Town Of Us 2.1.4]
[Warning:Unhollower] Method Void AddRend(UnityEngine.Renderer, Int32) on type TownOfUs.RainbowMod.RainbowBehaviour has unsupported parameter Int32 id of type System.Int32
[Info   :Unhollower] Registered mono type TownOfUs.RainbowMod.RainbowBehaviour in il2cpp domain
[Info   :Unhollower] Registered mono type TownOfUs.Coroutines+Component in il2cpp domain
[Warning:   BepInEx] Skipping [ExtraRoles 1.2.0] because it has a dependency that was not loaded. See previous errors for details.
[Message:   BepInEx] Chainloader startup complete
Setting breakpad minidump AppID = 945360
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198056794150 [API loaded no]
[Error  :Town Of Us] Couldn't generate hats0020
[Error  :Town Of Us] Couldn't generate hats0021
[Error  :Town Of Us] Couldn't generate hats0022
[Error  :Town Of Us] Couldn't generate hats0023
[Error  :Town Of Us] Couldn't generate hats0024
[Error  :Town Of Us] Couldn't generate hats0025
[Error  :Town Of Us] Couldn't generate hats0026
[Error  :Town Of Us] Couldn't generate hats0030
[Error  :Town Of Us] Couldn't generate hats0031
[Error  :Town Of Us] Couldn't generate hats0032
[Error  :Town Of Us] Couldn't generate hats0033
[Error  :Town Of Us] Couldn't generate hats0034
[Error  :Town Of Us] Couldn't generate hats0035
[Error  :Town Of Us] Couldn't generate hats0036
[Error  :Town Of Us] Couldn't generate hats0037
[Error  :Town Of Us] Couldn't generate hats0038
[Error  :Town Of Us] Couldn't generate hats0039
[Error  :Town Of Us] Couldn't generate hats0040
[Error  :Town Of Us] Couldn't generate hats0041
[Error  :Town Of Us] Couldn't generate hats0065
[Error  :Town Of Us] Couldn't generate misc0000
[Error  :Town Of Us] Couldn't generate misc0001
[Error  :Town Of Us] Couldn't generate misc0002
[Error  :Town Of Us] Couldn't generate misc0003
[Error  :Town Of Us] Couldn't generate misc0004
[Error  :Town Of Us] Couldn't generate misc0005
[Error  :Town Of Us] Couldn't generate misc0006
[Error  :Town Of Us] Couldn't generate misc0007
[Error  :Town Of Us] Couldn't generate misc0008
[Error  :Town Of Us] Couldn't generate misc0009
[Error  :Town Of Us] Couldn't generate misc0010
[Error  :Town Of Us] Couldn't generate misc0011
[Error  :Town Of Us] Couldn't generate misc0012
[Error  :Town Of Us] Couldn't generate misc0013
[Error  :Town Of Us] Couldn't generate misc0014
[Error  :Town Of Us] Couldn't generate misc0015
[Error  :Town Of Us] Couldn't generate misc0016
[Error  :Town Of Us] Couldn't generate misc0017
[Error  :Town Of Us] Couldn't generate misc0018
[Error  :Town Of Us] Couldn't generate misc0019
[Error  :Town Of Us] Couldn't generate misc0020
[Error  :Town Of Us] Couldn't generate misc0021
[Error  :Town Of Us] Couldn't generate misc0022
[Error  :Town Of Us] Couldn't generate misc0023
[Error  :Town Of Us] Couldn't generate misc0024
[Error  :Town Of Us] Couldn't generate misc0025
[Error  :Town Of Us] Couldn't generate misc0026
[Error  :Town Of Us] Couldn't generate misc0027
[Error  :Town Of Us] Couldn't generate misc0028
[Error  :Town Of Us] Couldn't generate misc0029
[Error  :Town Of Us] Couldn't generate standard0000
[Error  :Town Of Us] Couldn't generate standard0001
[Error  :Town Of Us] Couldn't generate standard0002
[Error  :Town Of Us] Couldn't generate standard0003
[Error  :Town Of Us] Couldn't generate standard0004
[Error  :Town Of Us] Couldn't generate standard0005
[Error  :Town Of Us] Couldn't generate standard0006
[Error  :Town Of Us] Couldn't generate standard0007
[Error  :Town Of Us] Couldn't generate standard0008
[Error  :Town Of Us] Couldn't generate standard0009
[Error  :Town Of Us] Couldn't generate standard0010
[Error  :Town Of Us] Couldn't generate standard0011
[Error  :Town Of Us] Couldn't generate standard0012
[Error  :Town Of Us] Couldn't generate standard0013
[Error  :Town Of Us] Couldn't generate standard0014
[Error  :Town Of Us] Couldn't generate standard0015
[Error  :Town Of Us] Couldn't generate standard0016
[Error  :Town Of Us] Couldn't generate standard0017
[Error  :Town Of Us] Couldn't generate standard0018
[Error  :Town Of Us] Couldn't generate standard0019
[Error  :Town Of Us] Couldn't generate standard0020
[Error  :Town Of Us] Couldn't generate standard0021
[Error  :Town Of Us] Couldn't generate standard0022
[Error  :Town Of Us] Couldn't generate standard0023
[Error  :Town Of Us] Couldn't generate standard0024
[Error  :Town Of Us] Couldn't generate standard0025
[Error  :Town Of Us] Couldn't generate standard0026
[Error  :Town Of Us] Couldn't generate standard0027
[Error  :Town Of Us] Couldn't generate standard0028
[Error  :Town Of Us] Couldn't generate standard0029
[Error  :Town Of Us] Couldn't generate standard0030
[Error  :Town Of Us] Couldn't generate standard0031
[Error  :Town Of Us] Couldn't generate standard0032
[Error  :Town Of Us] Couldn't generate standard0033
[Error  :Town Of Us] Couldn't generate standard0034
[Error  :Town Of Us] Couldn't generate standard0035
[Error  :Town Of Us] Couldn't generate standard0036
[Error  :Town Of Us] Couldn't generate standard0037
[Error  :Town Of Us] Couldn't generate standard0038
[Error  :Town Of Us] Couldn't generate myhats0000
[Error  :Town Of Us] Couldn't generate myhats0001
[Error  :Town Of Us] Couldn't generate myhats0002
[Error  :Town Of Us] Couldn't generate myhats0003
[Error  :Town Of Us] Couldn't generate myhats0004
[Error  :Town Of Us] Couldn't generate myhats0005
[Error  :Town Of Us] Couldn't generate myhats0006
[Error  :Town Of Us] Couldn't generate myhats0007
[Error  :Town Of Us] Couldn't generate myhats0008
[Error  :Town Of Us] Couldn't generate myhats0009
[Error  :Town Of Us] Couldn't generate myhats0010
[Error  :Town Of Us] Couldn't generate myhats0011
[Error  :Town Of Us] Couldn't generate myhats0012
[Error  :Town Of Us] Couldn't generate myhats0013
[Error  :Town Of Us] Couldn't generate myhats0014
[Error  :Town Of Us] Couldn't generate myhats0015
[Error  :Town Of Us] Couldn't generate myhats0016`

**Comment by cybershard** [comment]
Town Of Us is a standalone mod, please delete ExtraRoles, Essentials, and Reactor from your `BepInEx/plugins` folder.

**Comment by Quicky107** [comment]
Ok.

I have no more issue with the error loading,  but i still have 
"Couldn't generate hatsXXXX",
"Couldn't generate miscXXXX", etc...

An another thing, it's that the configuration of the game isn't be save when i leave the game. I have to set up again ratios and options of each role each time.

Thanks for ur help.
