### ISSUE TITLE
new colors break other mods/original game

### ISSUE THREAD

**Issue by rhonda** [polusgg/Town-Of-Us#24]
I am unsure if this is fixable with this mod at all, but when one uses one of the additional colors this mod offers, and one plays a different mod afterwards or the original game, you will show up only with three questionsmarks to others, you can't use the laptop in the lobby anymore to choose a different color, and also can't change your hat or skin.

Only after starting Town Of Us again, switching back to one of the original colors, and then going back into the other mod or vanilla game will enable you to use the laptop again.

Like said, I'm unsure if that's fixable from within this mod, but I think this issue should at least stay open for others to find the issue, and also see a solution on how to fix it when they encounter it.

**Comment by zukulent0** [comment]
Same issue as #15 so for a solution go and check it out
