### ISSUE TITLE
[Multiple Issues] Phantom is corporeal and Airship can't move

### ISSUE THREAD

**Issue by XTayuun** [polusgg/Town-Of-Us#242]
Multiple games tonight on Polus and Airship the Phantom would not be able to move through walls and was forced to wait for doors.

Also, multiple people in multiple games on airship would be fine the first round but after a meeting they would be unable to move. They could open the settings and change any settings but not open the map or ever move again. Another meeting would not resolve this issue. Bodies could not be reported by the impacted player either.

**Comment by NotSugden** [comment]
#237 resolves the first bug here

and the second bug will be fixed in the next release 👍

**Comment by XTayuun** [comment]
Fixed
