### ISSUE TITLE
Permanent hack after death and meeting

### ISSUE THREAD

**Issue by ProteinGolem** [polusgg/Town-Of-Us#250]
I was snitch, finishing my last task, water bottles. The glitch hacks me, I'm waiting for the water bottles to finish, but it didn't finish and the glitch kills me. The locks that indicate a glitch has hacked me appear on my screen and they stay in a particular location on the map afterwards, and never disappear.

As a killed dead player, you end up being permanently hacked and are unable to use admin table or vitals.

**Comment by NotSugden** [comment]
#248 will address this issue

**Comment by ProteinGolem** [comment]
Closing to reduce issue clutter. I will provide logs and reopen the issue if this happens again.
