### ISSUE TITLE
Submerged: Win conditions broken?

### ISSUE THREAD

**Issue by ProteinGolem** [polusgg/Town-Of-Us#252]
Watch this video and you will understand. :)
https://www.youtube.com/watch?v=7-vbbsAsUUw

- The arsonist's win condition relies on the death of all players.
- The jester's win condition gets overwritten by the Submerged map by checking for player spawn points, skipping checking for alternative win conditions

**Comment by parilynn** [comment]
Is this a map?

**Comment by ProteinGolem** [comment]
Submerged is a map that is jointly created by polus gg and 5up's team

**Comment by W-19** [comment]
Same deal with Executioner
