### ISSUE TITLE
Assassin doesn't work.

### ISSUE THREAD

**Issue by Kortingg** [polusgg/Town-Of-Us#254]
Assassins can't choose the role while voting. There's no opportunity to choose the role, it's completely invisible, It's possible only to cycle, but there's no roles. 
UPD: Cycle button doesn't work.

**Comment by Kortingg** [comment]
Cycle button doesn't work

**Comment by NotSugden** [comment]
this will be fixed in the 2.1.5/2.2 release

**Comment by mingyuxinli** [comment]
> 
> 
> 这将是固定的，在2.1.5/释放的2.2.0

So when will 2.1.5 version for 2021.6.30 release？Please Please Please Please Please Please
