### ISSUE TITLE
when will 2.1.5 version for 2021.6.30 release

### ISSUE THREAD

**Issue by balloplayz** [polusgg/Town-Of-Us#255]
im excited

**Comment by mingyuxinli** [comment]
I also want to ask this question, please

**Comment by jayzhan211** [comment]
Voting system can not see others votes

**Comment by qumqum22** [comment]
Assasin cannot choose role to delete

**Comment by iWalk809** [comment]
IS THIS REALLY A ISSUE? LMAO

**Comment by Eddiemate** [comment]
Really? Do we really want to rush an update out, when that could have more things broken? Do you guys not remember how 2.1.1 was? Have a little patience.

**Comment by balloplayz** [comment]
no idiot it doesnt take that long slushiegoose was faster at updating the mod than these idiots

**Comment by balloplayz** [comment]
shut up girl your a lier stop disliking comment

**Comment by NotSugden** [comment]
pick one
- fast and bad, with probably lots of issues
- a little bit slower and good, with minimal issues

**Comment by Eddiemate** [comment]
> no idiot it doesnt take that long slushiegoose was faster at updating the mod than these idiots

Wow, the person who wrote the mod for months was better at working on the spaghetti code than the person who picked it up a month ago? Even slushie says the code is hot garbage. The developer working on it is not only trying to make it easier to work in.
But hey, if these "idiots" trying to patch things and make the coding easier is taking too long then you can fork the mod for yourself and update it. It can't be that hard.

**Comment by ProteinGolem** [comment]
Solution: Pretend like the update is coming in a week or 2 weeks.

**Comment by balloplayz** [comment]
okay

**Comment by tartsharpcobra** [comment]
really?
