### ISSUE TITLE
[2.1.4.1?] Cannot complete towels on latest vanilla patch

### ISSUE THREAD

**Issue by robotgryphon** [polusgg/Town-Of-Us#257]
Towel assets are too big on x.30 build, send support.

![image](https://user-images.githubusercontent.com/8529636/125219029-1a57db00-e292-11eb-91ca-caf7ec669bc9.png)

**Comment by NotSugden** [comment]
is this not an issue with the base game? I don't see ToU changing this for any reason

**Comment by viper2kx** [comment]
This is a base game issue.
![image](https://user-images.githubusercontent.com/8532498/125472591-3894278c-f0cd-4772-9d98-4a6ca4d96af6.png)
