### ISSUE TITLE
Timelord nerf, or "button flash" fix?

### ISSUE THREAD

**Issue by ProteinGolem** [polusgg/Town-Of-Us#258]
Every time a kill or janitor event happens, the timelord button flashes. This makes timelord have a "2nd vitals" ability in essence. Due to this glitch, timelord knows exactly when to revive people. An alternative to the global timelord usage, timelord could instead be only able to use its ability either in radius to a body, or in a sabotage.

**Comment by ProteinGolem** [comment]
This issue is spam and I created a PR #261

**Comment by NotSugden** [comment]
if you put "fixes #x" in a PR description it automatically closes the issue when the PR is merged 👍
