### ISSUE TITLE
[Balancing] Make engineers in vents killable

### ISSUE THREAD

**Issue by kristibektashi** [polusgg/Town-Of-Us#263]
The engineer could theoretically stay in the vent all game and not die. So I have an idea to fix that. If the Impostor and the Engineer are in the same vent, the Impostor's kill button lights up (if it's not in cooldown). If the impostor presses the button the engineer dies and there is no bodybody for crewmates to report.

**Comment by viper2kx** [comment]
But you can't take action when ***in*** a vent. Even your cooldown pauses if you vent.

If an impostor is on a vent and the Engineer goes to the vent the impostor is on, they can kill the player in the vent. I managed to kill a number of engineers that way, and impostors (if I am sheriff). 

People in vents also show up on the admin table... so pretty sure it is pretty balanced already.

**Comment by kristibektashi** [comment]
> But you can't take action when _**in**_ a vent. Even your cooldown pauses if you vent.
> 
> If an impostor is on a vent and the Engineer goes to the vent the impostor is on, they can kill the player in the vent. I managed to kill a number of engineers that way, and impostors (if I am sheriff).
> 
> People in vents also show up on the admin table... so pretty sure it is pretty balanced already.

Oh, well in that case, it is pretty balanced already
