### ISSUE TITLE
Infinite Load?

### ISSUE THREAD

**Issue by ArchooD22** [polusgg/Town-Of-Us#267]
The little running crewmate will not stop running in circles, indicating that it's loading, forever. I don't know what to do, and the recommended steps have not worked (Spam Clicking),

**Comment by ssbastians** [comment]
i have this same exact issue. have you been able to find anything else on this?

**Comment by ArchooD22** [comment]
Fixed, you have to unzip the files into the folder. Drag the files from the
TOU_(number) folder/zip into the Town Of Us folder
