### ISSUE TITLE
Votes not shown

### ISSUE THREAD

**Issue by brianstepnitz** [polusgg/Town-Of-Us#270]
After voting, we can't see how many votes on anybody. We can't know how many skipped or anything.

Also found somebody on reddit having the same issue: https://www.reddit.com/r/AmongUsMods/comments/okepxm/votes_are_invisible_in_among_us_not_anonymous_vote/

**Comment by cheeriospank** [comment]
We are having the same problem, only showing thumbs up instead of voted and doesn’t show the amount of votes.

**Comment by Bublelift** [comment]
Overall the interface stopped working properly. For medic, altruist etc. the button says Kill instead of Use. Assassin role can't see which role he is cycling on certain person - can only shoot blind. We need 2.1.5 release ASAP!

**Comment by NotSugden** [comment]
town of us is not updated to among us 2021.6.30 (tbh that version is mega ugly anyway) downgrade to 2021.6.15 or wait until 2.2.0 is released

**Comment by ProteinGolem** [comment]
This issue is fixed.
