### ISSUE TITLE
All Roles' Buttons Do not Function due to player disconnect

### ISSUE THREAD

**Issue by ProteinGolem** [polusgg/Town-Of-Us#271]
This may be already fixed, but it is getting its own issue regardless. The last game in the logs provided demonstrate the bug. (Will provide logs in a moment)

Edit: My prior explanation was rather lacking. I've seen this issue occur in 2.1.3, before AU 2021.6.30 even had come out. All roles will lose their special role buttons and/or ability to function when a certain player disconnects/crashes, perhaps the host when a meeting is already in progress, or another player disconnects.

**Comment by ProteinGolem** [comment]
https://drive.google.com/file/d/1kOnWSFDhK8CJ-xMYTJbWjflIY41odwcK/view?usp=sharing

**Comment by NotSugden** [comment]
looks like this is on AU 2021.6.30, which TOU 2.1.4 does not support, downgrade to 2021.6.15

**Comment by ProteinGolem** [comment]
This issue may not be fixed but demands repeating before reopening for v2.2.0
