### ISSUE TITLE
Giant glitch cannot mimic?

### ISSUE THREAD

**Issue by ProteinGolem** [polusgg/Town-Of-Us#282]
I had a glitch game where I couldn't mimic, perhaps because I was giant?

**Comment by NotSugden** [comment]
please give more specific information

**Comment by ProteinGolem** [comment]
The logs are long gone. I'll have to experiment to reproduce the issue.

**Comment by NotSugden** [comment]
explain what the incorrect behaviour was, did the mimic buttons simply do nothing? did it not let you click anything? did it not even open the menu? etc
