### ISSUE TITLE
Black Screen when starting game

### ISSUE THREAD

**Issue by KoroS3n** [polusgg/Town-Of-Us#35]

**Comment by joelbladt** [comment]
Same Issue here.

**Comment by pepijno** [comment]
Same issue here, you here the sounds but no screen.

**Comment by rpet91** [comment]
Same issue here. It seems to work on The Skeld, but not on Polus

**Comment by ChristianAkacro** [comment]
Agreed, was able to play on Polus and Skeld fine, but anytime someone had a special new colour the game would blackscreen on us.

**Comment by MrF1uff** [comment]
This is only on the new version of among us also. The old 2020.12 version is fine

**Comment by JoelJ** [comment]
Can also confirm that this is resolved by not choosing a new color.

Is there a way to download a specific old version of Among Us to work around this bug?
