### ISSUE TITLE
Spy not listed on main page.

### ISSUE THREAD

**Issue by ChristianAkacro** [polusgg/Town-Of-Us#38]
Spy powers aren't listed on the main description page. Had to figure it out through experimentation.

**Comment by GotCubes** [comment]
Would you be able to explain what that role does? I haven't been able to figure it out.

**Comment by ChristianAkacro** [comment]
The spy has the power to see the colours of crew on the admin table, instead of everyone appearing as grey. I've also heard that it lets them see the length of time a body has been dead on vitals in the Polus Map, but I have not confirmed that personally.
