### ISSUE TITLE
Mods don't load in when using Boot Camp on Macbook

### ISSUE THREAD

**Issue by djinnXIX** [polusgg/Town-Of-Us#41]

**Comment by Pleiatus** [comment]
same problem on steam proton

**Comment by ccxex29** [comment]
Tried with Proton and KVM as well. Both don't work v2021.3.5s with the mod v1.1.0.

**Comment by Pleiatus** [comment]
https://github.com/NotHunter101/ExtraRolesAmongUs/issues/19
has solved the problem for wine (proton) by adding launch commands 
WINEDLLOVERRIDES="winhttp=n,b" %command%
