### ISSUE TITLE
Sidebar Settings Menu only works on 16:9 Monitors

### ISSUE THREAD

**Issue by MiningPickaxe** [polusgg/Town-Of-Us#42]
Hi, I just installed TownOfUs-v1.1.0-2021.3.5s.
When I run the game at my native 16:10 Aspect Ration (1920x1200) half of the menu is outside of the screen:
![image](https://user-images.githubusercontent.com/13851035/111366342-a7e43f00-8693-11eb-97df-3aac3cac3024.png)
When I manually change the resolution to 1920x1080 it works as intended.

**Comment by DorCoMaNdO** [comment]
May be an issue with Essentials, could you open an issue in my repo so I'll remember to look into this?
