### ISSUE TITLE
Multiple bugs/suggestions

### ISSUE THREAD

**Issue by nikander100** [polusgg/Town-Of-Us#49]
### Bugs
1.  If you have an executioner and the player they need to vote out gets killed. after that you vote out the imposter(s) the game keeps going until all tasks are complete.
2.  As timemaster if you report a body directly after  calling time shift the voting menu bugs out (doesnt allowed to vote)
3.  Engineer can fix every round (description states once per game)
4.  As imposter if camouflage is active and you are in a vent. when the camouflage ends, you get kicked out and ccan't move anymore.
5.  Reactor task clicking the 1-10 number: sometimes you cant click on the 7th number. so you cant win the game till you leave or get killed and then leave the game.
6.  Swapper: swapping with dead people crashes the game.

### Features
1.  Flash: give us a a setting to modify speed
2.  Sherrif: Make first round kill cooldown higher, or option to change it.
2.  Mayor: setting to set maximum votes they can gather.
3.  Setting for role/ability adjusting by 5%
4.  Setting to set sherrif kill cooldown for first round
5.  Spy: make spy ability a timed ability so he is not in spy mode all the time.
6.  Child: Make the child grow up to normal crewmate.
7.  Maybe far fetched but maybe support for 10+ player lobby's.

### Questions
1.  Can both Imposters also be lovers?
2.  Can the child also be a lover? if so, have an toggle option for it to not be possible.
3.  Can sherrif kill the executioner?

**Comment by nikander100** [comment]
Small update: bug added

**Comment by nikander100** [comment]
Small update: feature request added.

**Comment by Vorth-Ex** [comment]
There is also a bug with the swapper that makes it possible to swap votes with dead people and it makes the server/game crash

**Comment by nikander100** [comment]
> There is also a bug with the swapper that makes it possible to swap votes with dead people and it makes the server/game crash 

Will add it to the list 👍🏻

**Comment by zThana** [comment]
> 1. Can both Imposters also be lovers?
No, only 1 can become a loving impostor

> 2. Can the child also be a lover? if so, have an toggle option for it to not be possible.
No, they're both 2 primary roles and you can only have 1 with the exception of a loving impostor

> Spy: make spy ability a timed ability so he is not in spy mode all the time.
This should become a toggle may it be implemented

**Comment by Spartan322** [comment]
> > 1. Can both Imposters also be lovers?
> 
> No, only 1 can become a loving impostor
Might be interesting to add an option to allow this, one imposter gets killed, the other then, would say not to define limits, but might also be interesting on three imposter games.

**Comment by nikander100** [comment]
> three

yes exactly thats what i was thinking for 3 imposter games, and as 15 people lobby's will be a thing in the (near) future it could be really interesting (on the new airship map)
