### ISSUE TITLE
Important question

### ISSUE THREAD

**Issue by jonjonhtml** [polusgg/Town-Of-Us#58]
Hey i found someone on the internet that use your download link to the mod and say that he will give it only if his music video (that of course it has ads) will get one million views
No matter how many times i send the link on his comments from a lot of accounts he always deleted them is this legal?
Or it's something that i have to report to someone?
thx for helpers
 Jon

**Comment by joelbladt** [comment]
Yes, unfortunately it is legal. It is the channel of the content creator. If you really want to have the mod, keep searching via google. Then you come here on github to this repository. I feel sorry for the people who get screwed by the content creator in this way.

Kind regards
