### ISSUE TITLE
Learning from your code.

### ISSUE THREAD

**Issue by Thiladon** [polusgg/Town-Of-Us#62]
Hi ! I am a french student in computer science who's trying to learn a bit from himself by making project, and since I use Unity and play Among Us a lot with friend, I wanted to make mod for them, which so lead me here, reviewing ur code to learn how does BepInEx works etc.

I've understand a lot about the libraries / dependencies that I need to import, and even understand ur code, yet I still have an issue when I try to replicate at least the VersionShowerUpdate patch.

I did import every dependences I need, and my code show no error, it even build correctly into a .dll file, yet when I put it in the plugins folder of my BepInEx folder inside Among Us, then launch the game, the text that's supposed to show the version is nowhere to be seen :x

Here is my main class :

```cs
using BepInEx;
using BepInEx.IL2CPP;
using BepInEx.Logging;
using HarmonyLib;
using Reactor;
using Reactor.Extensions;
using Reactor.Unstrip;

namespace Hall_of_Us
{
    [BepInPlugin("com.thilladon.hallofus", "Hall of Us", "0.0.1")]
    [BepInDependency(ReactorPlugin.Id)]
    [BepInProcess("Among Us.exe")]
    public class HallOfUs : BasePlugin
    {
        public const string Id = "com.thilladon.hallofus";

        public Harmony Harmony { get; } = new Harmony(Id);
        public static ManualLogSource log;

        public override void Load()
        {
            log = Log;

            log.LogMessage("Thilladon's mod loaded !");


            Harmony.PatchAll();
        }
    }
}
```
& my VersionShowerUpdate.cs file :

```cs
using BepInEx.IL2CPP;
using HarmonyLib;
using UnityEngine;

namespace TownOfUs
{

    [HarmonyPatch(typeof(VersionShower), nameof(VersionShower.Start))]
    public static class VersionShowerUpdate
    {
        [HarmonyPostfix]
        [HarmonyPatch]
        [HarmonyPriority(Priority.First)]
        public static void Load(VersionShower __instance)
        {
            var text = __instance.text;
            //text.Text += "\nloaded [FFBFCCFF]T[FF80D5FF]o[FFCC00FF]w[704FA8FF]n[FF0000FF] of[CC4D00FF] Us [FFFFFFFF]by [00FF00FF]slushiegoose[FFFFFFFF] ";
            text.Text += "\n\n\n\n\n\n\n[00FF00FF]loaded Hall of Us Mod v0.0.1 by Thilladon[]";
        }
    }
}
```

**Comment by MrFawkes1337** [comment]
in VersionShowerUpdate, rename namespace TownOfUs to namespace HallOfUs

**Comment by Thiladon** [comment]
Oh, I'm soooo stupid, I was tired when copying that code, but should'nt VS supposed to show an error there ? :x

**Comment by MrFawkes1337** [comment]
[HarmonyPatch(typeof(VersionShower), nameof(VersionShower.Start))]
    public static class VersionShowerPatch
    {
        static void Postfix(VersionShower __instance)
        {
            string spacer = new String('\n', 10);
            if (__instance.text.Text.Contains(spacer))
                __instance.text.Text += "\n[FFFFFFFF]- Line 1[ec1919FF]Line 1[FFFFFFFF] v1.0\n Line  [4D0268FF]Two";
            else
                __instance.text.Text += spacer + "[FFFFFFFF]Line 1 Main Menu [ec1919FF]Color[FFFFFFFF] Version\n[4D0268FF]Line 2 Main Menu[]";
        }
    }

    [HarmonyPatch(typeof(PingTracker), nameof(PingTracker.Update))]
    public static class PingTrackerPatch
    {
        static void Postfix(VersionShower __instance)
        {
            __instance.text.Text += "\n[ec1919FF]Custom Roles \n[00ffffFF]Version: " + BonusRolesPlugin.VersionString + "[FFFFFFFF]";
            __instance.text.Text += "\n\n[20B2AAFF]Line 2 Purple [4D0268FF]--Still Purple--[]\nLine 3 Lobby";
        }
    }
}
this is my VersionShowerPatch. you can try this if you'd like. add it to your VersionShower namespace, and remove your old stuff.
