### ISSUE TITLE
Child cannot empty trash on Polus

### ISSUE THREAD

**Issue by corhere** [polusgg/Town-Of-Us#64]
The Child role is unable to use the O2: Empty Trash task on the Polus map. The trash chute handle gets outlined in yellow when nearby but the Use button stays inactive and spacebar does not open the task.

TownOfUs v1.2.0
Among Us v2021.3.5s

**Comment by FearlessFlo** [comment]
This is a known issue. The child is to small to reach the Tasks. 
The developer tries to fix this as far as i know.
Maybe you can do the Tasks as the child is grows up during the game.
