### ISSUE TITLE
Downlaod

### ISSUE THREAD

**Issue by Bruised-Octopus** [polusgg/Town-Of-Us#73]
I've tried downloading the mod watching various videos to try and do it and none of them work. Every time I load Among us the mod is never included.
Could you explain (in simple terms, I'm meh with pc) how to include it?

Cheers

**Comment by VanillaChan6571** [comment]
This does not work for the newest update for among us. Since there is no mod core update for it anyway. We just have to wait for now. 👀

**Comment by Bruised-Octopus** [comment]
Sweet.
When will I know when the mod is able to be used?

**Comment by schimini** [comment]
@Bruised-Octopus now!
