### ISSUE TITLE
How to install it? 

### ISSUE THREAD

**Issue by bulat2960** [polusgg/Town-Of-Us#77]
Can somebody explain me how to install this mod correctly, please?

There are many issues about it, and people advise to install this:
https://aka.ms/vs/16/release/vc_redist.x86.exe

But it didn't help me. What I'm supposed to do?

**Comment by FearlessFlo** [comment]
The Town of Us Mod does not feature the newest Version of Among Us yet. You have to stay patient so far.
Follow the progress on discord.

https://discord.com/invite/bYSaT74KzT

**Comment by Chrisnet82** [comment]
So we are waiting for the fix for V2021.3.31.3s?
Is this the first priority?
