### ISSUE TITLE
Does the mod not work with the current version of among us?

### ISSUE THREAD

**Issue by Aero235** [polusgg/Town-Of-Us#78]
Been trying to get the mod to work for awhile and was wondering if it wasnt working cause of the latest update?

**Comment by brynnftw** [comment]
Doesn't currently with what is on git, but there are streamers using it right now, likely testing it. So hopefully the bugs will get worked out and it will be available to us soon

**Comment by Aero235** [comment]
Im looking to get the mod to stream. How can i get access to the version they are using

**Comment by brynnftw** [comment]
The streamers I see using it seem to have a connection with the developer. It has been documented that you can use the older version of the game and it will work, but for the latest we just have to be patient and wait.

**Comment by Aero235** [comment]
How would one get an older version

**Comment by brynnftw** [comment]
On the right side of the git page there is a discord server link. Join there and instructions are posted in on the chat threads. I believe in the one called announcements.

**Comment by Johnzaum** [comment]
I'm not able to install the mods, I can't find the link to the discord server, where can I find it?

**Comment by FearlessFlo** [comment]
The Town of Us Mod does not feature the newest Version of Among Us yet.
To keep up the progress you can join the Discord Channel.

https://discord.com/invite/bYSaT74KzT

**Comment by skatsikeas** [comment]
Hi guys, does version 2.0.0 of the mod also work for the Epic store version of the game that has a version of 2021.4.1e?
