### ISSUE TITLE
How to use the old colors?

### ISSUE THREAD

**Issue by Spoonfairy** [polusgg/Town-Of-Us#80]
Hi there, my group really loves this mod, but the color change is screwing with another mod we want to use.
Is there any way to use this mod with the default colors?

**Comment by MrFawkes1337** [comment]
The mod has the default colors, as well as custom. If you wanted to remove the custom colors, edit TownOfUs.cs and remove PalettePatch.Load() and ClassInjector.RegisterTypeInIl2Cpp<RainbowBehaviour>(); then rebuild.
