### ISSUE TITLE
[QUESTION] How to build sources (v2.0.0)

### ISSUE THREAD

**Issue by Hoax017** [polusgg/Town-Of-Us#84]
Hi ! 
I'm trying to compile sources by my self but it doesn't work.
Can you explain how to do please ?

![image](https://user-images.githubusercontent.com/8215575/114187027-d75f3200-9947-11eb-9ef9-5c709ecf08bc.png)

**Comment by C0Nd3Mnd** [comment]
Are you opening the project file ([`TownOfUs.csproj`](sources/TownOfUs.csproj), not to be confused with [`TownOfUs.cs`](sources/TownOfUs.cs))?

**Comment by Hoax017** [comment]
@C0Nd3Mnd  Yes I open de .csproj

**Comment by amsyarasyiq** [comment]
> Hi ! 
> I'm trying to compile sources by my self but it doesn't work.
> Can you explain how to do please ?
> 
> ![image](https://user-images.githubusercontent.com/8215575/114187027-d75f3200-9947-11eb-9ef9-5c709ecf08bc.png)
> 

do you have BepInEx with Reactor inside your Among Us folder? do you have set `AmongUs` variables to your game's directory?

**Comment by Hoax017** [comment]
@amsyarasyiq thanks for your reply!
![image](https://user-images.githubusercontent.com/8215575/115536453-1a9b9800-a29a-11eb-8e08-67b209060eaf.png)
![image](https://user-images.githubusercontent.com/8215575/115536555-369f3980-a29a-11eb-9092-e4cea228da34.png)
I think all is good ?! 🤔

**Comment by amsyarasyiq** [comment]
Is building other mod works for you?

**Comment by devPrzemuS** [comment]
how to set AmongUs variable?
