### ISSUE TITLE
My mod wont work 

### ISSUE THREAD

**Issue by Dr-Venexii** [polusgg/Town-Of-Us#85]
I downloaded the most recent version of "Town of Us" and launched my game. once it launched it looked like my normal among us and the mods were not there. I tried different methods and they all led to the same thing happening. why does the latest version not work?

**Comment by DiogoNSS** [comment]
I'm having the same problem.

**Comment by FlirtyMomma** [comment]
> I'm having the same problem.

Hey. I can try to help you. Just add me on discord.

Squishy#0787

**Comment by DiogoNSS** [comment]
> > I'm having the same problem.
> 
> Hey. I can try to help you. Just add me on discord.
> 
> Discord: Squishy#787

the # is incomplete

**Comment by FlirtyMomma** [comment]
Yeah, sorry, the 0 seems to disappear

**Comment by DiogoNSS** [comment]
> Yeah, sorry, the 0 seems to disappear. Put it in bold and it stays xD

its ok

**Comment by FlirtyMomma** [comment]
> I'm having the same problem.

Issue fixed

**Comment by StatsRG** [comment]
> > I'm having the same problem.
> 
> Issue fixed

h o w

**Comment by FlirtyMomma** [comment]
> > > I'm having the same problem.
> > 
> > 
> > Issue fixed
> 
> h o w

Issue Fixed + 5 other people that dm'd me xD

**Comment by Anisha95-pi** [comment]
> > > > I'm having the same problem.
> > > 
> > > 
> > > Issue fixed
> > 
> > 
> > h o w
> 
> Issue Fixed + 5 other people that dm'd me xD

I tried dming you but your user name does not show anymore. I am facing the same issue. My discord is Anisha#9809.

**Comment by Anisha95-pi** [comment]
> > > > > I'm having the same problem.
> > > > 
> > > > 
> > > > Issue fixed
> > > 
> > > 
> > > h o w
> > 
> > 
> > Issue Fixed + 5 other people that dm'd me xD
> 
> I tried dming you but your user name does not show anymore. I am facing the same issue. My discord is Anisha#9809.

PLEASE HELP lol

**Comment by dpauli** [comment]
Its a problem with old stuff. Do this:

- Uninstall the game.
- Delete the Among Us folder under steamapps
- Reinstall Among Us.
- (!) Start the game without the mod, first.
- Install the Mod.
- Have fun.

The important thing: You cant play the mod, if you use the "Beta Version" of Among Us.
