### ISSUE TITLE
Stuck in Airship Walls

### ISSUE THREAD

**Issue by FlirtyMomma** [polusgg/Town-Of-Us#86]
If the time lord rewinds time at the start of the round on the Airship map. then the crewmates that were on the walls before selecting a location get stuck. This is because the game puts all the players around a "table" like on Skeld, which players get rewound back into.

Simple fix would be to make a delay before the time lord can rewind time.

P.s. Is there an official Slushiegoose discord server? Edit: Nvm. I've found it.

**Comment by Szazlo** [comment]
I have had this issue too. It usually happens when the player getting rewinded travels a longer distance before the time ability is used. This fling the player out side the map. I am not sure but making the rewind animation slower or stopping everyone for a few second then rewinding could fix this.

**Comment by FlirtyMomma** [comment]
If you get rewound to a position on the gap platform thing then you also get glitched into the wall
