### ISSUE TITLE
Is the mod updated enough for the latest version? (Latest version is 2021.4.2a)

### ISSUE THREAD

**Issue by GithubMod-JustHereToDownload** [polusgg/Town-Of-Us#87]
I have Among Us' latest version, 2021.4.2a, and I believe the latest version here is for 31st March? It wouldn't work anyways. But it seems it does work for some people, may I please clarify and know what is happening?

**Comment by FlirtyMomma** [comment]
What do you mean? The mod updated about 12 hours ago. It runs on the latest version of Among Us. Some people are having issues starting the game. But it can be fixed

**Comment by GithubMod-JustHereToDownload** [comment]
The version it was said to be is 2021.3.31.3s, so for 31st March. The latest version which I have downloaded is 2021.4.2a, so therefore, yeah. I tried downloading it and it doesn't work, perhaps others haven't updated the game yet?

**Comment by VanillaChan6571** [comment]
Un-enroll the beta to play.

**Comment by GithubMod-JustHereToDownload** [comment]
> Un-enroll the beta to play.

What is BETA? Am I supposed to have it downloaded or not? I do not have it right now. I'll try once I understand. Maybe I'll Google Search later,

**Comment by MrFawkes1337** [comment]
You are either on Android (Judging from the 2021.4.2A), or you are on the Steam Beta. This mod works on PC Only, on the latest 2021.3.31.3S FULL RELEASE.

**Comment by GithubMod-JustHereToDownload** [comment]
I'm on PC, I don't know what that means. But I don't think I have Steam or BETA as I never downloaded Steam and I never changed Among Us to BETA. My Among Us version is 2021.4.2a though.

**Comment by FlirtyMomma** [comment]
> I'm on PC, I don't know what that means. But I don't think I have Steam or BETA as I never downloaded Steam and I never changed Among Us to BETA. My Among Us version is 2021.4.2a though.

Did you buy the game, if so where from. Just wondering if you're using a cracked version.

**Comment by MrFawkes1337** [comment]
> > I'm on PC, I don't know what that means. But I don't think I have Steam or BETA as I never downloaded Steam and I never changed Among Us to BETA. My Among Us version is 2021.4.2a though.
> 
> Did you buy the game, if so where from. Just wondering if you're using a cracked version.

he's 100% loading an android version. a is the Android Key, S is Steam, i is Itch. Not sure on iOS. Plus, latest android release is 2021.4.2a so... :/

**Comment by MrFawkes1337** [comment]
This is an issue relating to the Android Mobile port of Among us, which the mod does not support.

**Comment by GithubMod-JustHereToDownload** [comment]
> > > I'm on PC, I don't know what that means. But I don't think I have Steam or BETA as I never downloaded Steam and I never changed Among Us to BETA. My Among Us version is 2021.4.2a though.
> > 
> > 
> > Did you buy the game, if so where from. Just wondering if you're using a cracked version.
> 
> he's 100% loading an android version. a is the Android Key, S is Steam, i is Itch. Not sure on iOS. Plus, latest android release is 2021.4.2a so... :/

Thanks for the information. I'll try and work it out later.

**Comment by GithubMod-JustHereToDownload** [comment]
> > > > I'm on PC, I don't know what that means. But I don't think I have Steam or BETA as I never downloaded Steam and I never changed Among Us to BETA. My Among Us version is 2021.4.2a though.
> > > 
> > > 
> > > Did you buy the game, if so where from. Just wondering if you're using a cracked version.
> > 
> > 
> > he's 100% loading an android version. a is the Android Key, S is Steam, i is Itch. Not sure on iOS. Plus, latest android release is 2021.4.2a so... :/
> 
> Thanks for the information. I'll try and work it out later.

I might have a cracked version I don't know but that might be the problem. I don't know much about it.
