### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by dragonkill3r36** [polusgg/Town-Of-Us#89]
Whenever I try to go host a game, I end up with a black scree and can't do anything unless I hit esc which brings me back to the main menu. Is there a way to fix this?

**Comment by suzelli** [comment]
I also am having the same problem :(

**Comment by CBowlen** [comment]
I was getting the same error, make sure you are not opted into the beta version of the game. Once I removed the beta and reupdated the mod is running fine.

**Comment by suzelli** [comment]
> I was getting the same error, make sure you are not opted into the beta version of the game. Once I removed the beta and reupdated the mod is running fine.

which one is beta version? i uninstalled 2.0.0 and tried 1.2.0 and got the same black screen

**Comment by Wakamu** [comment]
> > I was getting the same error, make sure you are not opted into the beta version of the game. Once I removed the beta and reupdated the mod is running fine.
> 
> which one is beta version? i uninstalled 2.0.0 and tried 1.2.0 and got the same black screen

he ment the game, not the mod

**Comment by CBowlen** [comment]
> > > I was getting the same error, make sure you are not opted into the beta version of the game. Once I removed the beta and reupdated the mod is running fine.
> > 
> > 
> > which one is beta version? i uninstalled 2.0.0 and tried 1.2.0 and got the same black screen
> 
> he ment the game, not the mod

Yeah the actual game you need to not use the beta version of the game

**Comment by dragonkill3r36** [comment]
> > > > I was getting the same error, make sure you are not opted into the beta version of the game. Once I removed the beta and reupdated the mod is running fine.
> > > 
> > > 
> > > which one is beta version? i uninstalled 2.0.0 and tried 1.2.0 and got the same black screen
> > 
> > 
> > he ment the game, not the mod
> 
> Yeah the actual game you need to not use the beta version of the game

I checked and im already not opted for the beta so idk what I need to do

**Comment by dragonkill3r36** [comment]
i removed the mod and uninstalled all of the files and game and then reinstalled it and it is still having issues so i dont think its a mod issue i think its with my game
