### ISSUE TITLE
Game is hitching

### ISSUE THREAD

**Issue by TheEgg1** [polusgg/Town-Of-Us#93]
Every 2 seconds or so the game has a framedrop/freeze and it's not happening in normal.

The hitching seems to happen every second when colorblind comms is called.

**Comment by KellethDregar** [comment]
Same here, been messing with settings to see if anything fixes it. Still no luck.

**Comment by bendd221** [comment]
Same, couldn't find a solution yet.
capping the game at 30 fps somewhat eased it, but it's still not very playable.
some of our group has this problem and some does not!

**Comment by Conrade2021** [comment]
I thought I was the only one.
 It keeps stuttering every 2 secs and it becomes difficult to play especially while moving
