### ISSUE TITLE
Among Us updated and Town of Us 2.0.0 no longer works

### ISSUE THREAD

**Issue by BeingStella** [polusgg/Town-Of-Us#98]
My among us game in steam automatically updated and the mod no longer works. I've tried uninstalling and reinstalling with no luck.

**Comment by carleyr01** [comment]
yeah everyone as their games are updating are all having the same problems

**Comment by not-3than** [comment]
> My among us game in steam automatically updated and the mod no longer works. I've tried uninstalling and reinstalling with no luck.

Can confirm. A new update is most likely already being worked on.

**Comment by SlitheryBoy151** [comment]
ye same among us is updated you need to update the mod
